kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-conf
  namespace: cakephp-docker
data:
  default.conf: |-
    server {
        listen 80;

        root /srv/app/webroot/;
        index index.php;

        location / {
          try_files $uri /index.php?$args;
        }

        location ~ \.php$ {
            fastcgi_pass php:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_buffers 16 16k;
            fastcgi_buffer_size 32k;
            include fastcgi_params;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: cakephp-docker
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.19-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
            - name: app
              mountPath: /srv/app
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
        - name: app
          persistentVolumeClaim:
            claimName: app-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: cakephp-docker
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
