kind: ConfigMap
apiVersion: v1
metadata:
  name: php-ini
  namespace: cakephp-docker
  labels:
    app: php
data:
  php.ini: |
    extension=intl.so
    extension=pdo_mysql.so
    extension=sodium
    extension=zip.so
    zend_extension=opcache.so

    [php]
    session.auto_start = Off
    short_open_tag = Off
    opcache.interned_strings_buffer = 16
    opcache.max_accelerated_files = 20000
    opcache.memory_consumption = 256
    realpath_cache_size = 4096K
    realpath_cache_ttl = 600
    expose_php = off
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-conf
  namespace: cakephp-docker
  labels:
    app: nginx
data:
  default.conf: |-
    server {
        listen 80;

        root /application/webroot/;
        index index.php;

        location / {
          try_files $uri /index.php?$args;
        }

        location ~ \.php$ {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_buffers 16 16k;
            fastcgi_buffer_size 32k;
            include fastcgi_params;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-nginx-deployment
  namespace: cakephp-docker
  labels:
    app: php-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-nginx
  template:
    metadata:
      labels:
        app: php-nginx
    spec:
      containers:
        - name: php
          image: cnizzardini/cakephp-docker:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: php-secret
                  key: database-url
            - name: SECURITY_SALT
              valueFrom:
                secretKeyRef:
                  name: php-secret
                  key: cakephp-salt
            - name: DEBUG
              value: 'false'
          volumeMounts:
            - name: php-ini
              mountPath: /usr/local/etc/php/conf.d
            - name: application
              mountPath: /application
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - >
                    cp -r /srv/app/. /application/.

        - name: nginx
          image: nginx:1.19-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
            - name: application
              mountPath: /application
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - >
                    chmod 775 -R /application &&
                    chmod 777 -R /application/logs &&
                    chmod 777 -R /application/tmp

      volumes:
        - name: php-ini
          configMap:
            name: php-ini
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: default.conf
                path: default.conf
        - name: application
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: cakephp-docker
  labels:
    app: nginx
spec:
  selector:
    app: php-nginx
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002
---
apiVersion: v1
kind: Service
metadata:
  name: php
  namespace: cakephp-docker
  labels:
    app: php
spec:
  selector:
    app: php-nginx
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
