apiVersion: v1
kind: Secret
metadata:
  name: php-secret
  namespace: cakephp-docker
type: Opaque
data:
  database-url: bXlzcWw6Ly9yb290OnJvb3RAbXlzcWwtc2VydmljZS9jYWtlcGhwP2VuY29kaW5nPXV0ZjgmdGltZXpvbmU9VVRDJmNhY2hlTWV0YWRhdGE9dHJ1ZSZxdW90ZUlkZW50aWZpZXJzPWZhbHNlJnBlcnNpc3RlbnQ9ZmFsc2U=
