kind: ConfigMap
apiVersion: v1
metadata:
  name: php-ini
  namespace: cakephp-docker
data:
  php.ini: |
    extension=intl.so
    extension=pdo_mysql.so
    extension=sodium
    extension=zip.so
    zend_extension=opcache.so

    [php]
    session.auto_start = Off
    short_open_tag = Off
    opcache.interned_strings_buffer = 16
    opcache.max_accelerated_files = 20000
    opcache.memory_consumption = 256
    realpath_cache_size = 4096K
    realpath_cache_ttl = 600
    expose_php = off
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  namespace: cakephp-docker
  labels:
    app: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php
          #image: localhost:5005/cakephp-docker:4.2-latest
          image: cnizzardini/cakephp-docker:4.2-latest
          ports:
            - containerPort: 9000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: php-secret
                  key: database-url
          volumeMounts:
            - name: php-ini
              mountPath: /usr/local/etc/php/conf.d
            - name: app
              mountPath: /srv/app
      volumes:
        - name: php-ini
          configMap:
            name: php-ini
        - name: app
          persistentVolumeClaim:
            claimName: app-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pv-claim
  namespace: cakephp-docker
  labels:
    app: app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: php
  namespace: cakephp-docker
spec:
  selector:
    app: php
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
