apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  labels:
    app: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php
          #image: localhost:5005/cakephp-docker:4.2-latest
          image: cnizzardini/cakephp-docker:4.2-latest
          ports:
            - containerPort: 9000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: php-secret
                  key: database-url
          volumeMounts:
            - name: php-ini
              mountPath: /usr/local/etc/php/conf.d
            - name: app
              mountPath: /srv/app
      volumes:
        - name: php-ini
          configMap:
            name: php-ini
        - name: app
          persistentVolumeClaim:
            claimName: app-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pv-claim
  labels:
    app: app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: php
spec:
  selector:
    app: php
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
