version: '3.4'

services:
  php:
    build:
      context: ../
      dockerfile: .docker/Dockerfile
      target: cakephp_php
    env_file:
      - php.env.development
    environment:
      PHP_IDE_CONFIG: "serverName=localhost"
    volumes:
      - ../app:/srv/app
      - ./php/development:/usr/local/etc/php
      - ~/.ssh/:/home/root/.ssh
    depends_on:
      - db

  db:
    image: library/mysql:8
    command: mysqld --sql_mode="" --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - mysql.env.development
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3307:3306"

  web:
    image: nginx:1.19-alpine
    working_dir: /srv/app
    environment:
      TERM: Linux
    volumes:
      - ../app:/srv/app
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8080:80"
    depends_on:
      - php
volumes:
  data:
